import { useParams } from 'react-router-dom'

import { LinkStats } from '../components/stats/LinkStats'

export function Stats() {
  const { phrase } = useParams<{ phrase: string }>()
  const decodedPhrase = decodeURIComponent(phrase ?? '')

  return (
    <>
      <title>{`offnd.at - /${decodedPhrase}`}</title>
      <meta property='og:title' content={`offnd.at - /${decodedPhrase}`} />
      <meta
        property='og:description'
        content={`Stats for "${decodedPhrase}". One of the many offensive links generated by offnd.at.`}
      />
      <LinkStats phrase={decodedPhrase} />
    </>
  )
}
